# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/github/pull-request/add-assignee"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/github/pull-request/add-label-based-on-branch-name"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/github/pull-request/approve"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/github/pull-request/merge"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/github/pull-request/request-review"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/github/release/create"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/oh-dear/check/request-run"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/oh-dear/maintenance-period/start"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/oh-dear/maintenance-period/stop"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"

  - commit-message:
      include: "scope"
      prefix: "github-actions"
    directory: "/actions/phive/install"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
