# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "github-actions"
    cooldown:
      default-days: 7
    directories:
      - "/"
      - "/actions/composer/determine-cache-directory"
      - "/actions/composer/determine-root-version"
      - "/actions/composer/install"
      - "/actions/github/pull-request/add-assignee"
      - "/actions/github/pull-request/add-label-based-on-branch-name"
      - "/actions/github/pull-request/approve"
      - "/actions/github/pull-request/merge"
      - "/actions/github/pull-request/request-review"
      - "/actions/github/release/create"
      - "/actions/github/release/publish"
      - "/actions/oh-dear/check/request-run"
      - "/actions/oh-dear/maintenance-period/start"
      - "/actions/oh-dear/maintenance-period/stop"
      - "/actions/phive/install"
    groups:
      github-actions:
        applies-to: "version-updates"
        group-by: "dependency-name"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
