# https://github.com/probot/settings

branches:
  - name: "master"

    # https://developer.github.com/v3/repos/branches/#remove-branch-protection
    # https://developer.github.com/v3/repos/branches/#update-branch-protection

    protection:
      enforce_admins: false
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      restrictions:

        # https://developer.github.com/v3/repos/branches/#parameters-1

        # Note: User, app, and team restrictions are only available for organization-owned repositories.
        # Set to null to disable when using this configuration for a repository on a personal account.

        apps:
          - "dependabot-preview"
        teams: []
        users:
          - "ergebnis-bot"

# https://developer.github.com/v3/issues/labels/#create-a-label
# https://developer.github.com/v3/issues/labels/#update-a-label

labels:
  - name: "bug"
    color: "ee0701"
    description: ""

  - name: "dependency"
    color: "0366d6"
    description: ""

  - name: "enhancement"
    color: "0e8a16"
    description: ""

  - name: "question"
    color: "cc317c"
    description: ""

  - name: "security"
    color: "ee0701"
    description: ""

  - name: "stale"
    color: "eeeeee"
    description: ""

# https://developer.github.com/v3/repos/#edit

repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  archived: false
  default_branch: "master"
  delete_branch_on_merge: true
  description: ":heart: Provides default community health files for the @ergebnis organization."
  has_downloads: false
  has_issues: false
  has_pages: false
  has_projects: false
  has_wiki: false
  name: ".github"
  private: false

  # https://developer.github.com/v3/repos/branches/#remove-branch-protection

  topics: "default, community, health, files"
