# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
# https://getcomposer.org/doc/03-cli.md#composer-cache-dir

name: "Determine composer cache directory"

description: "Determines the composer cache directory and exports it as COMPOSER_CACHE_DIR environment variable"

inputs:
  working-directory:
    default: "."
    description: "Which directory to use as working directory"
    required: true

runs:
  using: "composite"

  steps:
    - name: "Determine composer cache directory"
      env:
        COMPOSER_DETERMINE_CACHE_DIRECTORY_WORKING_DIRECTORY: "${{ inputs.working-directory }}"
      run: | # zizmor: ignore[github-env]
        COMPOSER_CACHE_DIR="$(composer config cache-dir --working-dir="${COMPOSER_DETERMINE_CACHE_DIRECTORY_WORKING_DIRECTORY}")"

        echo "COMPOSER_CACHE_DIR=${COMPOSER_CACHE_DIR}" >> "${GITHUB_ENV}"
      shell: "bash"
