# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
# https://ohdear.app/docs/integrations/api/maintenance-windows#creating-a-new-maintenance-period-on-demand

name: "Starts maintenance period"

description: "Starts maintenance period"

inputs:
  oh-dear-api-token:
    description: "Oh Dear API token of a user with permission to start maintenance period"
    required: true
  oh-dear-site-id:
    description: "Site identifer of an Oh Dear site for which to start a maintenance period"
    required: true

runs:
  using: "composite"

  steps:
    - name: "Start maintenance period on ohdear.app"
      env:
        OH_DEAR_API_TOKEN: "${{ inputs.oh-dear-api-token }}"
        OH_DEAR_SITE_ID: "${{ inputs.oh-dear-site-id }}"
      run: |
        curl --url "https://ohdear.app/api/sites/${OH_DEAR_SITE_ID}/start-maintenance" \
          --fail \
          --header "Accept: application/json" \
          --header "Authorization: Bearer ${OH_DEAR_API_TOKEN}" \
          --header "Content-Type: application/json" \
          --request POST
      shell: "bash"
