# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
# https://docs.github.com/en/rest/releases/releases#update-a-release
# https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push

name: "Publish a release"

description: "Publishes a release"

inputs:
  github-token:
    description: "GitHub token of a user with permission to publish a release"
    required: true
  release-id:
    description: "The release identifier"
    required: true

runs:
  using: "composite"

  steps:
    - name: "Publish release"
      uses: "actions/github-script@v7.0.1"
      with:
        github-token: "${{ inputs.github-token }}"
        script: |
          try {
            const response = await github.rest.repos.updateRelease({
              draft: false,
              owner: context.repo.owner,
              release_id: ${{ inputs.release-id }},
              repo: context.repo.repo,
            });
          } catch (error) {
            core.setFailed(error.message);
          }
