# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"

permissions: {}

jobs:
  coding-standards:
    name: "Coding Standards"

    permissions:
      contents: "read"

    runs-on: "ubuntu-latest"

    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: "Lint YAML files"
        uses: "ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c" # v3.1.1
        with:
          config_file: ".yamllint.yaml"
          file_or_dir: "."
          strict: true

  github-actions-analysis:
    name: "GitHub Actions Analysis"

    permissions:
      contents: "read"

    runs-on: "ubuntu-latest"

    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          persist-credentials: false

      - name: "Run zizmorcore/zizmor-action"
        uses: "zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5" # v0.6.1
        with:
          advanced-security: false
          annotations: true
          inputs: ".github/"
