# https://docs.github.com/en/actions

name: "Merge"

on: # yamllint disable-line rule:truthy
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Integrate"

jobs:
  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == 'dependabot[bot]' && (
        startsWith(github.event.workflow_run.head_commit.message, 'github-actions(deps)')
      )

    steps:
      - name: "Request review from @ergebnis-bot"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0];
            const repository = context.repo;

            const reviewers = [
              "ergebnis-bot",
            ]

            await github.rest.pulls.requestReviewers({
              owner: repository.owner,
              repo: repository.repo,
              pull_number: pullRequest.number,
              reviewers: reviewers,
            });

      - name: "Assign @ergebnis-bot"
        uses: "./.github/actions/github/add-assignee-to-pull-request"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
          assignee: "ergebnis-bot"

      - name: "Approve pull request"
        uses: "./.github/actions/github/approve-pull-request"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"

      - name: "Merge pull request"
        uses: "./.github/actions/github/merge-pull-request"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
