# https://docs.github.com/en/actions

name: "Triage"

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types:
      - "opened"

jobs:
  label:
    name: "Label"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.4.0"

      - name: "Add labels based on branch name"
        uses: "./.github/actions/github/pull-request/add-label-based-on-branch-name"
        with:
          github-token: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
